# Generated by Django 6.0.7 on 2026-08-03 19:23

import django.core.validators
import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.PositiveIntegerField(db_index=True)),
                ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Water', 'Water'), ('Internet', 'Internet'), ('Rent', 'Rent'), ('Salary', 'Salary'), ('Supplies', 'Supplies'), ('Maintenance', 'Maintenance'), ('Gas/LPG', 'Gas/LPG'), ('Transportation', 'Transportation'), ('Other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('expense_date', models.DateField(db_index=True, default=expenses.models.business_date_today)),
                ('payee', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(default='CASH', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, upload_to='expense_receipts/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved')], default='APPROVED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-expense_date', '-created_at'),
            },
        ),
    ]
