# Generated by Django 6.0.7 on 2026-08-02 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_refreshtoken'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ROLE_CHANGED', 'Role changed'), ('DEACTIVATED', 'Account deactivated'), ('ACTIVATED', 'Account activated'), ('SOFT_DELETED', 'Account soft-deleted'), ('PASSWORD_RESET', 'Password reset by admin'), ('PROFILE_UPDATED', 'Profile updated by admin')], max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['restaurant', 'role'], name='accounts_us_restaur_629165_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['restaurant', 'is_active', 'is_deleted'], name='accounts_us_restaur_6798b1_idx'),
        ),
        migrations.AddField(
            model_name='staffaudit',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_actions_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffaudit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_audits', to='accounts.restaurant'),
        ),
        migrations.AddField(
            model_name='staffaudit',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_actions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='staffaudit',
            index=models.Index(fields=['restaurant', 'created_at'], name='accounts_st_restaur_dcfd64_idx'),
        ),
    ]
