# Generated by Django 6.0.7 on 2026-08-03 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.PositiveIntegerField(db_index=True)),
                ('type', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('NEW_ORDER', 'New order'), ('ORDER_CANCELLED', 'Order cancelled'), ('LARGE_DISCOUNT', 'Large discount'), ('CLOSING_REMINDER', 'Closing reminder'), ('PO_RECEIVED', 'PO received')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('target_role', models.CharField(blank=True, max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
