# Generated by Django 6.0.7 on 2026-08-03 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.PositiveIntegerField(db_index=True)),
                ('business_date', models.DateField(db_index=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='CLOSED', max_length=10)),
                ('reopen_reason', models.CharField(blank=True, max_length=255)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days_closed', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days_reopened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-business_date',),
                'unique_together': {('restaurant_id', 'business_date')},
            },
        ),
    ]
